// import { Employee } from './TS';

export const MockData = [
  {
    storyName: 'Enhance User Authentication System',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "50",
    storyId: '52729',
    startDate: '2014-04-10',
    targetDate: '2023-05-06',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In Progress',
    priority: 'Low',
    type: 'Task',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Redesign Dashboard interface',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "70",
    storyId: '71964',
    startDate: '2013-02-05  ',
    targetDate: '2014-04-10',
    attachment: 'C:\fakepath\dm.png	',
    status: 'Open',
    priority: 'Medium',
    type: 'Feature',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Implementation Advanced Report Features',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "20",
    storyId: '72551',
    startDate: '2014-04-10',
    targetDate: '2023-05-06',
    attachment: 'C:\fakepath\dm.png	',
    status: 'Closed',
    priority: 'High',
    type: 'Task',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Optimized Mobile Performance',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "99",
    storyId: '57801',
    startDate: '2018-02-10',
    targetDate: '2044-04-10',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'Medium',
    type: 'Feature',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
];
