// import { Employee } from './TS';

export const MockData = [
  {
    storyName: 'Enhance User Authentication System',
    progress: "50",
    storyId: '52729',
    startDate: '3/20/2014',
    targetDate: '2/20/2012',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'medium',
    type: 'features',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Redesign Dashboard interface',
    progress: "70",
    storyId: '71964',
    startDate: '3/9/2018',
    targetDate: '04/10/2008',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'medium',
    type: 'features',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Implementation Advanced Report Features',
    progress: "20",
    storyId: '72551',
    startDate: '8/12/2020',
    targetDate: '2/02/2002',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'medium',
    type: 'features',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
   },
  {
    storyName: 'Optimized Mobile Performance',
    progress: "99",
    storyId: '57801',
    startDate: '7/22/2017',
    targetDate: '7/25/2017',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'medium',
    type: 'features',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
];
