// import { Employee } from './TS';

export const MockData = [
  {
    storyName: 'Enhance User Authentication System',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "50",
    storyId: '52729',
    startDate: '03/09/2014',
    targetDate: '02/04/2012',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In Progress',
    priority: 'Low',
    type: 'Task',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Redesign Dashboard interface',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "70",
    storyId: '71964',
    startDate: '03/09/2018',
    targetDate: '04/10/2008',
    attachment: 'C:\fakepath\dm.png	',
    status: 'Open',
    priority: 'Medium',
    type: 'Feature',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Implementation Advanced Report Features',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "20",
    storyId: '72551',
    startDate: '08/12/2020',
    targetDate: '02/02/2002',
    attachment: 'C:\fakepath\dm.png	',
    status: 'Closed',
    priority: 'High',
    type: 'Task',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
  {
    storyName: 'Optimized Mobile Performance',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    progress: "99",
    storyId: '57801',
    startDate: '07/07/2017',
    targetDate: '07/02/2017',
    attachment: 'C:\fakepath\dm.png	',
    status: 'In progress',
    priority: 'Medium',
    type: 'Feature',
    component: 'asdf',
    sprint: 'asdf',
    labels: 'asdfasdf',
    tickets: 'asdfasdf',
  },
];
